/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nlopt4j_optimizer_NLopt */

#ifndef _Included_org_nlopt4j_optimizer_NLopt
#define _Included_org_nlopt4j_optimizer_NLopt
#ifdef __cplusplus
extern "C" {
#endif
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT 0L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L 1L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L_RAND
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L_RAND 2L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_NOSCAL
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_NOSCAL 3L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L_NOSCAL
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L_NOSCAL 4L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L_RAND_NOSCAL
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_DIRECT_L_RAND_NOSCAL 5L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_ORIG_DIRECT
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_ORIG_DIRECT 6L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_ORIG_DIRECT_L
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_ORIG_DIRECT_L 7L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GD_STOGO
#define org_nlopt4j_optimizer_NLopt_NLOPT_GD_STOGO 8L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GD_STOGO_RAND
#define org_nlopt4j_optimizer_NLopt_NLOPT_GD_STOGO_RAND 9L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_LBFGS_NOCEDAL
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_LBFGS_NOCEDAL 10L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_LBFGS
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_LBFGS 11L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_PRAXIS
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_PRAXIS 12L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_VAR1
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_VAR1 13L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_VAR2
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_VAR2 14L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON 15L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON_RESTART
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON_RESTART 16L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON_PRECOND
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON_PRECOND 17L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON_PRECOND_RESTART
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_TNEWTON_PRECOND_RESTART 18L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_CRS2_LM
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_CRS2_LM 19L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_MLSL
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_MLSL 20L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GD_MLSL
#define org_nlopt4j_optimizer_NLopt_NLOPT_GD_MLSL 21L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_MLSL_LDS
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_MLSL_LDS 22L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GD_MLSL_LDS
#define org_nlopt4j_optimizer_NLopt_NLOPT_GD_MLSL_LDS 23L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_MMA
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_MMA 24L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_COBYLA
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_COBYLA 25L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_NEWUOA
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_NEWUOA 26L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_NEWUOA_BOUND
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_NEWUOA_BOUND 27L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_NELDERMEAD
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_NELDERMEAD 28L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_SBPLX
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_SBPLX 29L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_AUGLAG
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_AUGLAG 30L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_AUGLAG
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_AUGLAG 31L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_AUGLAG_EQ
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_AUGLAG_EQ 32L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_AUGLAG_EQ
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_AUGLAG_EQ 33L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LN_BOBYQA
#define org_nlopt4j_optimizer_NLopt_NLOPT_LN_BOBYQA 34L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_ISRES
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_ISRES 35L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_AUGLAG
#define org_nlopt4j_optimizer_NLopt_NLOPT_AUGLAG 36L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_AUGLAG_EQ
#define org_nlopt4j_optimizer_NLopt_NLOPT_AUGLAG_EQ 37L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_G_MLSL
#define org_nlopt4j_optimizer_NLopt_NLOPT_G_MLSL 38L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_G_MLSL_LDS
#define org_nlopt4j_optimizer_NLopt_NLOPT_G_MLSL_LDS 39L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_SLSQP
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_SLSQP 40L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_LD_CCSAQ
#define org_nlopt4j_optimizer_NLopt_NLOPT_LD_CCSAQ 41L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_GN_ESCH
#define org_nlopt4j_optimizer_NLopt_NLOPT_GN_ESCH 42L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_NUM_ALGORITHMS
#define org_nlopt4j_optimizer_NLopt_NLOPT_NUM_ALGORITHMS 43L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_FAILURE
#define org_nlopt4j_optimizer_NLopt_NLOPT_FAILURE -1L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_INVALID_ARGS
#define org_nlopt4j_optimizer_NLopt_NLOPT_INVALID_ARGS -2L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_OUT_OF_MEMORY
#define org_nlopt4j_optimizer_NLopt_NLOPT_OUT_OF_MEMORY -3L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_ROUNDOFF_LIMITED
#define org_nlopt4j_optimizer_NLopt_NLOPT_ROUNDOFF_LIMITED -4L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_FORCED_STOP
#define org_nlopt4j_optimizer_NLopt_NLOPT_FORCED_STOP -5L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_SUCCESS
#define org_nlopt4j_optimizer_NLopt_NLOPT_SUCCESS 1L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_STOPVAL_REACHED
#define org_nlopt4j_optimizer_NLopt_NLOPT_STOPVAL_REACHED 2L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_FTOL_REACHED
#define org_nlopt4j_optimizer_NLopt_NLOPT_FTOL_REACHED 3L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_XTOL_REACHED
#define org_nlopt4j_optimizer_NLopt_NLOPT_XTOL_REACHED 4L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_MAXEVAL_REACHED
#define org_nlopt4j_optimizer_NLopt_NLOPT_MAXEVAL_REACHED 5L
#undef org_nlopt4j_optimizer_NLopt_NLOPT_MAXTIME_REACHED
#define org_nlopt4j_optimizer_NLopt_NLOPT_MAXTIME_REACHED 6L
/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_nlopt4j_optimizer_NLopt_create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_min_objective
 * Signature: (JLorg/nlopt4j/optimizer/NLopt/NLopt_func;)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1min_1objective
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_max_objective
 * Signature: (JLorg/nlopt4j/optimizer/NLopt/NLopt_func;)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1max_1objective
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    add_inequality_constraint
 * Signature: (JLorg/nlopt4j/optimizer/NLopt/NLopt_func;D)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_add_1inequality_1constraint
  (JNIEnv *, jclass, jlong, jobject, jdouble);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    add_equality_constraint
 * Signature: (JLorg/nlopt4j/optimizer/NLopt/NLopt_func;D)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_add_1equality_1constraint
  (JNIEnv *, jclass, jlong, jobject, jdouble);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_lower_bounds
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1lower_1bounds
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_upper_bounds
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1upper_1bounds
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_maxeval
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1maxeval
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_maxtime
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1maxtime
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_stop_value
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1stop_1value
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    optimize
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_org_nlopt4j_optimizer_NLopt_optimize
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_local_optimizer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1local_1optimizer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    set_xtol_rel
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_set_1xtol_1rel
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_nlopt4j_optimizer_NLopt
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nlopt4j_optimizer_NLopt_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_nlopt4j_optimizer_NLopt_NLopt_func */

#ifndef _Included_org_nlopt4j_optimizer_NLopt_NLopt_func
#define _Included_org_nlopt4j_optimizer_NLopt_NLopt_func
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
